[package]
name = "ccp_copa"
version = "0.1.1"
authors = ["Venkat Arun <venkatar@mit.edu>"]

[dependencies]
clap = "2.29"
portus = { git = "https://github.com/ccp-project/portus", branch = "many_to_one" }
slog = "2"
slog-async = "2"
slog-term = "2"
time = "0.1"

[dependencies.nom]
version = "4"
features = ["verbose-errors"]
