[package]
name = "ccp_copa"
version = "0.1.1"
authors = ["Venkat Arun <venkatar@mit.edu>"]

[dependencies]
clap = "2.29"
fnv = "1"
portus = { path = "/home/frank/portus" }
portus_export = { path = "/home/frank/portus/portus_export" }
slog = "2"
slog-async = "2"
slog-term = "2"
time = "0.1"
